name: Run JMeter Tests and Publish Report

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      test-folder:
        description: 'Folder containing test plans to execute (e.g., test_plans/folder1)'
        required: false
        default: 'test_plans'

permissions:
  id-token: write
  contents: write
  pages: write

jobs:
  run-jmeter-tests:
    runs-on: ubuntu-latest

    env:
      JMETER_VERSION: 5.5
      ARTIFACT_NAME: "jmeter-reports-${{ github.run_id }}"  # Using run_id to ensure unique artifact name

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Java 17
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Install JMeter
      - name: Install JMeter
        run: |
          wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-${{ env.JMETER_VERSION }}.tgz
          tar -xzf apache-jmeter-${{ env.JMETER_VERSION }}.tgz
          sudo mv apache-jmeter-${{ env.JMETER_VERSION }} /opt/jmeter

      # Step 4: Add JMeter to PATH
      - name: Add JMeter to PATH
        run: |
          echo "PATH=$PATH:/opt/jmeter/bin" >> $GITHUB_ENV

      # Step 5: Verify JMeter version
      - name: Verify JMeter version
        run: |
          jmeter --version

      # Step 6: Set Test Folder
      - name: Set Test Folder
        id: set-folder
        run: |
          if [[ -z "${{ github.event.inputs.test-folder }}" ]]; then
            echo "TEST_FOLDER=test_plans" >> $GITHUB_ENV
          else
            echo "TEST_FOLDER=${{ github.event.inputs.test-folder }}" >> $GITHUB_ENV
          fi

      # Step 7: Run all JMeter Test Plans in the Selected Folder
      - name: Run JMeter Test Plans in Selected Folder
        run: |
          echo "Using test folder: $TEST_FOLDER"
          mkdir -p ${{ github.workspace }}/report
          for test_plan in ${{ github.workspace }}/$TEST_FOLDER/*.jmx; do
            echo "Running test plan: $test_plan"
            result_file="${test_plan%.jmx}.jtl"
            jmeter -n -t "$test_plan" -l "$result_file"
            
            # Generate HTML report for each test plan
            report_dir="${test_plan%.jmx}-report"
            jmeter -g "$result_file" -e -o "$report_dir"

            # Move the generated report into the main report folder
            mv "$report_dir" ${{ github.workspace }}/report/$(basename "${test_plan%.jmx}")
          done

      # Step 8: Upload All HTML Reports as a Single Artifact
      - name: Upload All HTML Reports as a Single Artifact
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-reports-${{ github.run_id }}  # Dynamic artifact name
          path: ${{ github.workspace }}/report
          retention-days: 1

  deploy-to-pages:
    needs: run-jmeter-tests
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      # Step 1: Download all artifacts from the previous job
      - name: Download all JMeter report artifacts
        uses: actions/download-artifact@v4
        with:
          name: jmeter-reports-${{ github.run_id }}  # Use the same dynamic artifact name
          path: reports

      # Step 2: Setup Pages for GitHub Pages deployment
      - name: Setup Pages
        uses: actions/configure-pages@v4

      # Step 3: Prepare reports directory
      - name: Prepare reports directory
        run: |
          mkdir -p _site
          # Generate an index.html file with links to the reports
          echo "<html><body><h1>JMeter Test Reports</h1><ul>" > _site/index.html
          for report in reports/*; do
            echo "<li><a href=\"$report\">$(basename $report)</a></li>" >> _site/index.html
          done
          echo "</ul></body></html>" >> _site/index.html

      # Step 4: Upload Pages artifact for GitHub Pages
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
