name: Run JMeter Tests and Publish Report

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      test-folder:
        description: 'Folder containing test plans to execute (e.g., test_plans/folder1)'
        required: false
        default: 'test_plans'

permissions:
  id-token: write
  contents: write
  pages: write  # Required for GitHub Pages deployment

jobs:
  run-jmeter-tests:
    runs-on: ubuntu-latest

    env:
      JMETER_VERSION: 5.5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install JMeter
        run: |
          wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-${{ env.JMETER_VERSION }}.tgz
          tar -xzf apache-jmeter-${{ env.JMETER_VERSION }}.tgz
          sudo mv apache-jmeter-${{ env.JMETER_VERSION }} /opt/jmeter

      - name: Add JMeter to PATH
        run: |
          echo "PATH=$PATH:/opt/jmeter/bin" >> $GITHUB_ENV

      - name: Verify JMeter version
        run: |
          jmeter --version

      - name: Set Test Folder
        id: set-folder
        run: |
          if [[ -z "${{ github.event.inputs.test-folder }}" ]]; then
            echo "TEST_FOLDER=test_plans" >> $GITHUB_ENV
          else
            echo "TEST_FOLDER=${{ github.event.inputs.test-folder }}" >> $GITHUB_ENV
          fi

      - name: Run JMeter Test Plans in Selected Folder
        run: |
          echo "Using test folder: $TEST_FOLDER"
          mkdir -p ${{ github.workspace }}/report
          for test_plan in ${{ github.workspace }}/$TEST_FOLDER/*.jmx; do
            echo "Running test plan: $test_plan"
            result_file="${test_plan%.jmx}.jtl"
            jmeter -n -t "$test_plan" -l "$result_file"
            
            # Generate HTML report for each test plan
            report_dir="${test_plan%.jmx}-report"
            jmeter -g "$result_file" -e -o "$report_dir"

            # Move the generated report into the main report folder
            mv "$report_dir" ${{ github.workspace }}/report/$(basename "${test_plan%.jmx}")
          done

      - name: List contents before uploading artifact
        run: |
          echo "Contents of report folder:"
          ls -R ${{ github.workspace }}/report  # List contents of the report folder

      - name: Upload All HTML Reports as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: jmeter-reports
          path: ${{ github.workspace }}/report
          retention-days: 1  # Retention period of 1 day

  deploy-to-pages:
    needs: run-jmeter-tests
    runs-on: ubuntu-latest

    permissions:
      pages: write  # Required for GitHub Pages deployment
      id-token: write  # For OIDC authentication

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          name: jmeter-reports
          path: reports  # Ensure it matches the upload path

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Prepare reports directory
        run: |
          mkdir -p _site
          cp reports/*/index.html _site/index.html

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
