name: Run JMeter Tests and Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      test-folder:
        description: 'Folder containing test plans to execute (e.g., test_plans/folder1)'
        required: false
        default: 'test_plans'

permissions:
  id-token: write
  contents: write

jobs:
  run-jmeter-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install JMeter
        run: |
          wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.5.tgz
          tar -xzf apache-jmeter-5.5.tgz
          sudo mv apache-jmeter-5.5 /opt/jmeter

      - name: Add JMeter to PATH
        run: echo "PATH=$PATH:/opt/jmeter/bin" >> $GITHUB_ENV

      - name: Verify JMeter version
        run: jmeter --version

      - name: Set Test Folder
        run: |
          if [[ -z "${{ github.event.inputs.test-folder }}" ]]; then
            echo "TEST_FOLDER=test_plans" >> $GITHUB_ENV
          else
            echo "TEST_FOLDER=${{ github.event.inputs.test-folder }}" >> $GITHUB_ENV
          fi
           
      - name: Install JMeter Plugins Manager
        run: |
          wget https://repo1.maven.org/maven2/kg/apc/jmeter-plugins-manager/1.3/jmeter-plugins-manager-1.3.jar \
            -O /opt/jmeter/lib/ext/jmeter-plugins-manager-1.3.jar
          wget https://repo1.maven.org/maven2/kg/apc/cmdrunner/2.2/cmdrunner-2.2.jar \
            -O /opt/jmeter/lib/cmdrunner-2.2.jar

      - name: Generate PluginsManagerCMD helper
        run: |
         java -cp /opt/jmeter/lib/ext/jmeter-plugins-manager-1.3.jar:/opt/jmeter/lib/cmdrunner-2.2.jar \
         org.jmeterplugins.repository.PluginManagerCMDInstaller

      - name: Install specific plugin globally (jpgc-tst)
        run: |
         # Download jpgc-tst plugin to plugin cache
         java -jar /opt/jmeter/lib/cmdrunner-2.2.jar \
         --tool org.jmeterplugins.repository.PluginManagerCMD \
         install jpgc-tst

      - name: Verify global plugin installation
        run: |
          echo "Installed plugin JARs in lib/ext:"
          ls /opt/jmeter/lib/ext | grep jpgc-tst || echo "jpgc-tst plugin not found!"

      - name: Run JMeter Test Plans
        run: |
          echo "Using test folder: $TEST_FOLDER"
          mkdir -p ${{ github.workspace }}/report
          for test_plan in ${{ github.workspace }}/$TEST_FOLDER/*.jmx; do
            echo "Installing required plugins for $test_plan"
            java -jar /opt/jmeter/lib/cmdrunner-2.2.jar \
            --tool org.jmeterplugins.repository.PluginManagerCMD \
            install-for-jmx "$test_plan"
            
            echo "Running test plan: $test_plan"
            result_file="${test_plan%.jmx}.jtl"
            jmeter -n -t "$test_plan" -l "$result_file"
            
            report_dir="${test_plan%.jmx}-report"
            jmeter -g "$result_file" -e -o "$report_dir"

            mv "$report_dir" ${{ github.workspace }}/report/$(basename "${test_plan%.jmx}")
          done

      - name: Upload JMeter Reports as an Artifact
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-reports
          path: ${{ github.workspace }}/report
          retention-days: 1

  deploy-to-pages:
    needs: run-jmeter-tests
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Download JMeter Reports Artifact
        uses: actions/download-artifact@v4
        with:
          name: jmeter-reports
          path: reports

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Create index.html
        run: |
          echo "<html><body><h1>JMeter Test Reports</h1><ul>" > reports/index.html
          for report_dir in reports/*; do
            if [ -d "$report_dir" ]; then
              report_name=$(basename "$report_dir")
              echo "<li><a href=\"$report_name/index.html\">$report_name</a></li>" >> reports/index.html
            fi
          done
          echo "</ul></body></html>" >> reports/index.html

      - name: Upload Reports to GitHub Pages
        uses: actions/upload-pages-artifact@v4
        with:
          path: reports

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
