name: Run JMeter Tests and Publish Report

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
    inputs:
      test-folder:
        description: 'Folder containing test plans to execute (e.g., test_plans/folder1)'
        required: false
        default: 'test_plans' # Default folder for test plans

permissions:
  id-token: write
  contents: write

jobs:
  run-jmeter-tests:
    runs-on: ubuntu-latest

    env:
      JMETER_VERSION: 5.5

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install Java 17
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Install JMeter
      - name: Install JMeter
        run: |
          wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-${{ env.JMETER_VERSION }}.tgz
          tar -xzf apache-jmeter-${{ env.JMETER_VERSION }}.tgz
          sudo mv apache-jmeter-${{ env.JMETER_VERSION }} /opt/jmeter

      # Step 4: Add JMeter to PATH
      - name: Add JMeter to PATH
        run: |
          echo "PATH=$PATH:/opt/jmeter/bin" >> $GITHUB_ENV

      # Step 5: Verify JMeter version
      - name: Verify JMeter version
        run: |
          jmeter --version

      # Step 6: Set Test Folder
      - name: Set Test Folder
        id: set-folder
        run: |
          if [[ -z "${{ github.event.inputs.test-folder }}" ]]; then
            echo "TEST_FOLDER=test_plans" >> $GITHUB_ENV
          else
            echo "TEST_FOLDER=${{ github.event.inputs.test-folder }}" >> $GITHUB_ENV
          fi

      # Step 7: Run all JMeter Test Plans in the Selected Folder
      - name: Run JMeter Test Plans in Selected Folder
        run: |
          echo "Using test folder: $TEST_FOLDER"
          for test_plan in ${{ github.workspace }}/$TEST_FOLDER/*.jmx; do
            echo "Running test plan: $test_plan"
            jmeter -n -t "$test_plan" -l "$test_plan.jtl"
          done

      # Step 8: Generate HTML Reports for Each Test Plan
      - name: Generate HTML Reports for Each Test Plan
        run: |
          mkdir -p ${{ github.workspace }}/report
          for result_file in ${{ github.workspace }}/$TEST_FOLDER/*.jtl; do
            report_dir="${result_file%.jtl}-report"
            jmeter -g "$result_file" -e -o "$report_dir"
            mv "$report_dir" ${{ github.workspace }}/report/
          done

      # Step 9: Upload all HTML Reports as Artifact
      - name: Upload HTML Reports as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: jmeter-reports
          path: ${{ github.workspace }}/report
