name: Run JMeter Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-jmeter-tests:
    runs-on: ubuntu-latest

    env:
      JMETER_VERSION: 5.5 # Define the JMeter version as a variable

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install JMeter
        run: |
          wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-${{ env.JMETER_VERSION }}.tgz
          tar -xzf apache-jmeter-${{ env.JMETER_VERSION }}.tgz
          sudo mv apache-jmeter-${{ env.JMETER_VERSION }} /opt/jmeter

      - name: Verify JMeter version
        run: |
          /opt/jmeter/bin/jmeter --version

      - name: Debug file existence
        run: |
          echo "Listing files in extras folder:"
          ls -l ${{ github.workspace }}/extras

      - name: Run testing .jmx file from extras folder
        run: |
          /opt/jmeter/bin/jmeter -n -t ${{ github.workspace }}/extras/Test.jmx -l ${{ github.workspace }}/extras/results.jtl

      - name: Run test.jmx file from Test_plans/ folder
        run: |
          /opt/jmeter/bin/jmeter -n -t ${{ github.workspace }}/Test_plans/test.jmx -l ${{ github.workspace }}/Test_plans/results.jtl

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: jmeter-test-results
          path: |
            extras/results.jtl
            Test_plans/results.jtl
