name: Run JMeter Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-jmeter-tests:
    runs-on: ubuntu-latest

    env:
      JMETER_VERSION: 5.5 # Define the JMeter version as a variable

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install JMeter
        run: |
          wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-${{ env.JMETER_VERSION }}.tgz
          tar -xzf apache-jmeter-${{ env.JMETER_VERSION }}.tgz
          sudo mv apache-jmeter-${{ env.JMETER_VERSION }} /opt/jmeter

      - name: Verify JMeter version
        run: |
          /opt/jmeter/bin/jmeter --version

      - name: Debug installed JMeter extras folder
        run: |
          echo "Listing files in JMeter extras folder:"
          ls -l /opt/jmeter/extras

      - name: Run default Test.jmx from JMeter extras folder
        run: |
          /opt/jmeter/bin/jmeter -n -t /opt/jmeter/extras/Test.jmx -l /opt/jmeter/extras/results.jtl

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: jmeter-test-results
          path: /opt/jmeter/extras/results.jtl
