name: Run JMeter Tests and Publish Report

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-jmeter-tests:
    runs-on: ubuntu-latest

    env:
      JMETER_VERSION: 5.5 # Define the JMeter version as a variable

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install Java 17
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Install JMeter
      - name: Install JMeter
        run: |
          wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-${{ env.JMETER_VERSION }}.tgz
          tar -xzf apache-jmeter-${{ env.JMETER_VERSION }}.tgz
          sudo mv apache-jmeter-${{ env.JMETER_VERSION }} /opt/jmeter

      # Step 4: Add JMeter to PATH
      - name: Add JMeter to PATH
        run: |
          echo "PATH=$PATH:/opt/jmeter/bin" >> $GITHUB_ENV

      # Step 5: Verify JMeter version
      - name: Verify JMeter version
        run: |
          jmeter --version

      # Step 6: Run JMeter Test Plan and Generate Results
      - name: Run JMeter Test Plan and Generate Results
        run: |
          jmeter -n -t ${{ github.workspace }}/test_plans/demo.jmx -l ${{ github.workspace }}/test_plans/results.jtl

      # Step 7: Generate HTML Report from JMeter Results
      - name: Generate HTML Report
        run: |
          jmeter -g ${{ github.workspace }}/test_plans/results.jtl -e -o ${{ github.workspace }}/report

      # Step 8: Upload the report folder as artifact (to be used for deployment)
      - name: Upload HTML Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: jmeter-report
          path: ${{ github.workspace }}/report

  deploy-to-pages:
    runs-on: ubuntu-latest
    needs: run-jmeter-tests
    steps:
      # Step 9: Download the report artifact
      - name: Download HTML Report Artifact
        uses: actions/download-artifact@v3
        with:
          name: jmeter-report

      # Step 10: Deploy the HTML Report to GitHub Pages
      - name: Deploy HTML Report to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          branch: gh-pages
          folder: report
