name: Run JMeter Tests and Publish Report

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
    inputs:
      test-folder:
        description: 'Folder containing test plans to execute (e.g., test_plans/folder1)'
        required: true
        default: 'test_plans/demo.jmx'

permissions:
  id-token: write
  contents: write

jobs:
  run-jmeter-tests:
    runs-on: ubuntu-latest

    env:
      JMETER_VERSION: 5.5

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install Java 17
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Install JMeter
      - name: Install JMeter
        run: |
          wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-${{ env.JMETER_VERSION }}.tgz
          tar -xzf apache-jmeter-${{ env.JMETER_VERSION }}.tgz
          sudo mv apache-jmeter-${{ env.JMETER_VERSION }} /opt/jmeter

      # Step 4: Add JMeter to PATH
      - name: Add JMeter to PATH
        run: |
          echo "PATH=$PATH:/opt/jmeter/bin" >> $GITHUB_ENV

      # Step 5: Verify JMeter version
      - name: Verify JMeter version
        run: |
          jmeter --version

      # Step 6: Run all JMeter Test Plans in the Selected Folder
      - name: Run JMeter Test Plans in Selected Folder
        run: |
          for test_plan in ${{ github.workspace }}/$INPUT_TEST-FOLDER/*.jmx; do
            echo "Running test plan: $test_plan"
            jmeter -n -t "$test_plan" -l "$test_plan.jtl"
          done

      # Step 7: Generate HTML Reports for Each Test Plan
      - name: Generate HTML Reports for Each Test Plan
        run: |
          mkdir -p ${{ github.workspace }}/report
          for result_file in ${{ github.workspace }}/$INPUT_TEST-FOLDER/*.jtl; do
            report_dir="${result_file%.jtl}-report"
            jmeter -g "$result_file" -e -o "$report_dir"
            mv "$report_dir" ${{ github.workspace }}/report/
          done

      # Step 8: Upload all HTML Reports as Artifact
      - name: Upload HTML Reports as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: jmeter-reports
          path: ${{ github.workspace }}/report

  deploy-to-pages:
    runs-on: ubuntu-latest
    needs: run-jmeter-tests
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      # Step 9: Download the report artifact
      - name: Download HTML Report Artifact
        uses: actions/download-artifact@v3
        with:
          name: jmeter-reports

      # Step 10: Deploy the HTML Reports to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
